
services:
  web:
    build: ./docker/apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html   
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dwes_t3_rpg_clase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend_network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db  
      MYSQL_ROOT_PASSWORD: rootpassword  
    ports:
      - "8081:80"  
    depends_on:
      - db
    networks:
      - backend_network
      
networks:
  backend_network:
    driver: bridge